### ISSUE TITLE
java.nio.channels.ClosedByInterruptException

### ISSUE THREAD

**Issue by mrdear** [osiegmar/logback-gelf#16]
My project is used 1.1.0 version, however, I found my log can not be sent to graylog server, the exception is java.nio.channels.ClosedByInterruptException.

I do not know why this is so I put the relevant screenshots up.

This is an exception,`de.siegmar.logbackgelf.AbstractGelfAppender#append`

![image](https://user-images.githubusercontent.com/13889883/35279236-6b7c25f4-0087-11e8-942b-e9d7dbf1b466.png)

This is current channel
![image](https://user-images.githubusercontent.com/13889883/35279421-0350a9c2-0088-11e8-9ba0-c0cbba09a18a.png)

My kafka  dependency

```xml
   <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.10</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by osiegmar** [comment]
I assume that a connection couldn't be established. But that's hard to say without a complete stacktrace -- please provide one.

**Comment by mrdear** [comment]
First Exception is
```java
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:473)
	at de.siegmar.logbackgelf.GelfUdpAppender.appendMessage(GelfUdpAppender.java:83)
	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:106)
	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:28)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.log4j.Category.differentiatedLog(Category.java:193)
	at org.apache.log4j.Category.warn(Category.java:249)
	at kafka.utils.Logging$class.warn(Logging.scala:83)
	at kafka.consumer.SimpleConsumer.warn(SimpleConsumer.scala:29)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:76)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:71)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:109)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:109)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:109)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:108)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:108)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:108)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:107)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:96)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:88)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:51)
```


And  after this, the exception become

```java
java.nio.channels.ClosedChannelException
	at sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:320)
	at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:428)
	at de.siegmar.logbackgelf.GelfUdpAppender.appendMessage(GelfUdpAppender.java:83)
	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:106)
	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:28)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
	at ch.qos.logback.classic.Logger.log(Logger.java:765)
	at org.apache.log4j.Category.differentiatedLog(Category.java:193)
	at org.apache.log4j.Category.warn(Category.java:249)
	at kafka.utils.Logging$class.warn(Logging.scala:83)
	at kafka.consumer.ZookeeperConsumerConnector.warn(ZookeeperConsumerConnector.scala:79)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance$3$$anonfun$apply$10.apply(ZookeeperConsumerConnector.scala:488)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance$3$$anonfun$apply$10.apply(ZookeeperConsumerConnector.scala:477)
	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance$3.apply(ZookeeperConsumerConnector.scala:477)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance$3.apply(ZookeeperConsumerConnector.scala:464)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.kafka$consumer$ZookeeperConsumerConnector$ZKRebalancerListener$$rebalance(ZookeeperConsumerConnector.scala:464)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anonfun$syncedRebalance$1.apply$mcVI$sp(ZookeeperConsumerConnector.scala:408)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener.syncedRebalance(ZookeeperConsumerConnector.scala:402)
	at kafka.consumer.ZookeeperConsumerConnector$ZKRebalancerListener$$anon$1.run(ZookeeperConsumerConnector.scala:355)
```

**Comment by osiegmar** [comment]
Have you modified the logback-gelf version you're using? [Line 83 of GelfUdpAppender.java of version 1.1.0](https://github.com/osiegmar/logback-gelf/blob/d160771682d56597fbdc5be2edb80244416e2f38/src/main/java/de/siegmar/logbackgelf/GelfUdpAppender.java#L83) doesn't contain code. The actual send invocation is in line 81.

The exception (ClosedByInterruptException) and stacktraces looks like that you're application (or the thread) is shutdown while communicating with graylog. The same applies for the ClosedChannelException -- the channel is closed when stopping the logback appender.

Try this to test:

```java
import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.LoggerContext;
import de.siegmar.logbackgelf.GelfLayout;
import de.siegmar.logbackgelf.GelfUdpAppender;

public class Test {

    private static final String HOST = "localhost";
    private static final int PORT = 12201;

    public static void main(String[] args) {
        final Logger logger = setupLogger(true);

        logger.error("Test message");

        stopLogger(logger);
    }

    private static Logger setupLogger(final boolean useCompression) {
        final LoggerContext lc = (LoggerContext) LoggerFactory.getILoggerFactory();

        final GelfLayout gelfLayout = new GelfLayout();
        gelfLayout.setContext(lc);
        gelfLayout.setOriginHost("localhost");
        gelfLayout.start();

        final Logger logger = (Logger) LoggerFactory.getLogger(Test.class);
        logger.addAppender(buildAppender(useCompression, lc, gelfLayout));
        logger.setAdditive(false);

        return logger;
    }

    private static GelfUdpAppender buildAppender(final boolean useCompression,
                                                 final LoggerContext lc,
                                                 final GelfLayout gelfLayout) {
        final GelfUdpAppender gelfAppender = new GelfUdpAppender();
        gelfAppender.setContext(lc);
        gelfAppender.setName("GELF");
        gelfAppender.setLayout(gelfLayout);
        gelfAppender.setGraylogHost(HOST);
        gelfAppender.setGraylogPort(PORT);
        gelfAppender.setUseCompression(useCompression);
        gelfAppender.start();
        return gelfAppender;
    }

    private static void stopLogger(final Logger logger) {
        final GelfUdpAppender gelfAppender = (GelfUdpAppender) logger.getAppender("GELF");
        gelfAppender.stop();
    }

}
```

**Comment by mrdear** [comment]
Yes, when I tried to solve the problem, I added some output statements.

But I did not find the problem,let me check this issue again on weekends.

Thank you for your help.
