### ISSUE TITLE
 Error sending GELF message java.nio.channels.AsynchronousCloseException

### ISSUE THREAD

**Issue by zhongyiio** [osiegmar/logback-gelf#36]
```
23:31:04,825 |-ERROR in de.siegmar.logbackgelf.GelfUdpAppender[GELF_UDP] - Error sending GELF message java.nio.channels.AsynchronousCloseException
	at java.nio.channels.AsynchronousCloseException
	at 	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at 	at java.base/sun.nio.ch.DatagramChannelImpl.endWrite(DatagramChannelImpl.java:693)
	at 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:533)
	at 	at de.siegmar.logbackgelf.GelfUdpAppender.appendMessage(GelfUdpAppender.java:81)
	at 	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:106)
	at 	at de.siegmar.logbackgelf.AbstractGelfAppender.append(AbstractGelfAppender.java:28)
	at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at 	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at 	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at 	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at 	at ch.qos.logback.classic.Logger.filterAndLog_2(Logger.java:414)
	at 	at ch.qos.logback.classic.Logger.info(Logger.java:587)
```

**Comment by osiegmar** [comment]
Please update. This bug should be fixed by #20 in 2.0.1.
